jwt:
  key:
    access: VGFlaG9vblNpZGVQcm9qZWN0DQo=
    refresh: UmVmcmVzaFRhZWhvb24=
  max-age:
    access: 1800 # 60 * 30
    refresh: 604800 # 60 * 60 * 24 * 7

spring:
  # Database Setting
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://140.238.204.161:3306/community?serverTimezone=Australia/Sydney&useUnicode=true&characterEncoding=utf8
      #      jdbc-url: jdbc:mariadb://localhost:3306/comm?serverTimezone=Australia/Sydney&useUnicode=true&characterEncoding=utf8
      username: root
      password: xoGNS12!@